yatube/posts/urls.py
# posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name = 'posts'),
    path('index.html', views.index, name = 'post_index'),
    path('group/<slug:slug>/', views.group_posts, name = 'group'),
    path('group_list.html', views.group_list, name = 'group_list'),
] 

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    def __str__(self):
        return f'{[self.title]!r}' 
    title = models.TextField()
    slug = models.TextField()
    description = models.TextField()


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    ) 
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.CASCADE) 

yatube/post/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
# Главная страница

def index(request):
    template = 'posts/index.html'
    return render(request, template) 


def group_posts(request, slug):
    return HttpResponse(f'Пост {slug}')

yatube/posts/views.py
from django.shortcuts import render
from .models import Post
# Create your views here.
# Главная страница


def index(request):
    # Одна строка вместо тысячи слов на SQL:
    # в переменную posts будет сохранена выборка из 10 объектов модели Post,
    # отсортированных по полю pub_date по убыванию (от больших значений к меньшим)
    posts = Post.objects.order_by('-pub_date')[:10]
    # В словаре context отправляем информацию в шаблон
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context) 


def group_list(request):
    template = 'posts/group_list.html'
    return render(request, template) 


def group_posts(request, slug):
    template = 'posts/group_posts.html'
    text = 'Здесь будет информация о группах проекта Yatube'
    context = {
        'text': text,
        'slug': slug
              }
    return render(request, template, context) 

yatube/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html> 
<html lang="ru">          
  <head>
    {% load static %}   
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <title>
        {% block title %}
        {% endblock %} 
    </title>       
  </head>
  <body>       
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
        <div class="container py-5">
      {% block content %}
      Рандомный контент
      {% endblock %}
        </div>
    </main>
    <footer>
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html> 

yatube/templates/includes/footer.html
<footer class="page-footer font-small blue border-top">
    <div class="footer-copyright text-center py-3">© 2020 Copyright 
      <p><span style="color:red">Ya</span>tube</p> 
    </div>    
  </footer>

yatube/templates/includes/header.html
<header>
  {% load static %}
  <link rel="stylesheet" href="css/bootstrap.min.css">
    <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
    <!-- В дальнейшем тут будет создано полноценное меню -->
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class="navbar-brand" href="{% url 'posts:post_index' %}">
          <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
          <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
          <span style="color:red">Ya</span>tube
        </a>
      </div>
    </nav>      
  </header>

yatube/templates/posts/group_list.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
{% extends 'base.html' %}
  
  {% block content %}
        <h1>Лев Толстой – зеркало русской революции.</h1>
        <p>
          Группа тайных поклонников графа.
        </p>
        <article>
          <ul>
            <li>
              Автор: Лев Толстой
            </li>
            <li>
              Дата публикации: 30 июля 1854
            </li>
          </ul>      
          <p>
            [Рымник.] Сдѣлалъ верхомъ переходъ до Рымника. [[5]] Старикъ все не кланяется мнѣ.
            Обѣ вещи эти злятъ меня. Съ встрѣчавшимися баши-бузуками велъ себя хорошо. 
            Объяснился съ Крыжановскимъ. Онъ, не знаю зачѣмъ, совѣтуетъ мнѣ прикомандироваться 
            къ казачьей батареѣ; совѣтъ, которому я не послѣдую. Желчно спорилъ вечеромъ съ Фриде 
            и Бабарыкинымъ, ругалъ Сержпутовскому и ничего не сдѣлалъ, вотъ 3 упрека, которыя дѣлаю с
            ебѣ за нынѣшній день. (3)
          </p>         
        </article>
        <hr>
        <article>
          <ul>
            <li>
              Автор: Лев Толстой
            </li>
            <li>
              Дата публикации: 29 июля 1854
            </li>
          </ul> 
          <p>
            Исправленіе мое идетъ прекрасно. Я чувствую, какъ отношенія мои становятся пріятны и легки 
            съ людьми всякаго рода, съ тѣхъ поръ какъ я рѣшился быть скромнымъ и убѣдился въ томъ, 
            что казаться всегда величественнымъ и непогрѣшнымъ вовсе не есть необходимость. Я очень 
            веселъ. И дай Богъ, какъ мнѣ кажется, — чтобы веселье это происходило отъ самаго меня; 
            отъ желаній всѣмъ быть пріятнымъ, скромности, необидчивости и внимательности за вспышками. 
            — Тогда бы я всегда былъ веселъ и почти всегда счастливъ. 
            Утромъ рѣшилъ было сидѣть дома, позаниматься, но дѣло не пошло и не утерпѣлъ вечеромъ, 
            чтобы не пойдти пошляться. Идя отъ ужина, мы съ Тишк[евичемъ] остановились у бардели и насъ 
            накрылъ Крыжановскій, что, признаюсь, было мнѣ не совсѣмъ пріятно. Упрекаю себя за 
            безхарактерность, что не высидѣлъ дома, и зa праздность цѣлаго дня. Это главный пунктъ. (2)
          </p>      
        </article>
        <hr>
        <article>
          <ul>
            <li>
              Автор: Лев Толстой
            </li>
            <li>
              Дата публикации: 28 июля 1854
            </li>
          </ul> 
          <p>
            Пишу въ самомъ пріятномъ веселомъ расположеніи духа, въ которомъ я провелъ весь вечеръ. 
            Утро читалъ, объѣдался грушами и вмѣсто обѣда ѣлъ сыръ. Несмотря на кутежи у Сталыпина и 
            Сержпутовскаго по случаю полученія наградъ, не завидовалъ, а провелъ день весело. Вечеромъ 
            хватилъ босонож[ку] и выпилъ бокала два шампанскаго съ Шварц[емъ], Вейлеровскимъ [?] и 
            Гембичомъ, потомъ болталъ съ Шубинымъ и съ Сашей Горчаковымъ. — Исключая праздности, 
            днемъ своимъ очень доволенъ. (1)
          </p>
        </article>
        <!-- под последним постом нет линии -->
      </div>  
      {% endblock %}
</html>

yatube/templates/posts/group_posts.html
<!DOCTYPE html>
<html lang="ru">
<html>
  <head>
    <title> пост {{ slug }}</title>
  </head>
  <body>
    <h1>{{ text }}</h1>
    <p> пост {{ slug }} </p>
  </body>
</html> 

yatube/templates/posts/index.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
{% extends 'base.html' %}
 
   
    {% block title %}{{ text }}{% endblock %} 
  
  {% block content %}
  {% for post in posts %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>    
  <a href="">все записи группы</a>
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %} 
      {% endblock %}
</html>